Repository dbt-labs/dbt-docs, pull requests merged in 2023-02, with the labels that each got.

#351 remove PR from changie yaml template
  .changie.yaml
Labels: cla:yes, Skip Changelog

#367 Fix JSON path to overview docs
  .changes/unreleased/Docs-20230209-082901.yaml
  src/app/overview/index.js
Labels: cla:yes, ready_for_review

#371 Searchable column descriptions
  .changes/unreleased/Docs-20230209-212729.yaml
  src/app/components/search/search.html
  src/app/components/search/search.js
  src/app/services/project_service.js
Labels: cla:yes, ready_for_review

#359 Improve displayed message under "Arguments" section for argumentless macro
  .changes/unreleased/Docs-20230113-094855.yaml
  src/app/components/macro_arguments/index.html
Labels: cla:yes, ready_for_review

#376 add access property
  .changes/unreleased/Docs-20230227-114510.yaml
  package-lock.json
  src/app/components/table_details/table_details.js
Labels: cla:yes

#382 Add model owner from group, standardize exposure owner
  .changes/unreleased/Docs-20230227-141424.yaml
  src/app/components/table_details/table_details.js
  src/app/docs/exposure.js
Labels: cla:yes

#385 revert from #376
  .gitignore
  .tool-versions
  package-lock.json
Labels: cla:yes, Skip Changelog
