Repository dbt-labs/dbt-docs, pull requests merged in 2023-03, with the labels that each got.

#389 change node shape based on access type.
  .changes/unreleased/Docs-20230307-104219.yaml
  src/app/services/graph.service.js
Labels: cla:yes

#391 Fix JSON path to package overview docs
  .changes/unreleased/Docs-20230307-174951.yaml
  package-lock.json
  src/app/overview/index.js
Labels: cla:yes, ready_for_review

#393 Revert change to package-lock.json in #391
  package-lock.json
Labels: cla:yes, Skip Changelog

#392 Add selection by group to DAG
  .changes/unreleased/Docs-20230308-093736.yaml
  src/app/services/selector_matcher.js
Labels: cla:yes

#398 Take two: distinguish nodes in DAG viz based on `access`
  .changes/unreleased/Docs-20230307-104219.yaml
  ci-project/dbt_project.yml
  ci-project/models/groups.yml
  ci-project/models/marts/core/schema.yml
  ci-project/models/staging/schema.yml
  data/catalog.json
  data/manifest.json
  package-lock.json
  src/app/services/graph.service.js
Labels: cla:yes
